### PR TITLE
Fix/sergio

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Review by rokusottervanger — COMMENTED** [review]
How did I get to be the author on this?

**Review by rokusottervanger — COMMENTED** [review]
Why is there a `start.launch` and a `start2.launch`?

**Comment by MatthijsBurgh** [comment]
Sorry, that commit was me.

We have two start launchfiles, because some IO is connected to SERGIO1 and some IO is connected to SERGIO2. Therefore we need two `start.launch`.

**Comment by rokusottervanger** [comment]
That's what the `machine` tags are for. We could just let the roscore autostart on sergio1 and autostart start.launch on sergio2 (with a --wait to make sure the roscore is online), with the `machine` tags specifying which machine to start the node on. That should work, right?

**Comment by rokusottervanger** [comment]
BTW, we should not create this kind of generic branches. Instead, we should fix isolated functionality on isolated branches.

**Comment by MatthijsBurgh** [comment]
This solution is more robust when rebooting only SERGIO2. Maybe good to hear a opinion of a third person.

**Review by rokusottervanger — APPROVED** [review]

**Pull request merged**
